### ISSUE TITLE
IsObject() missing function

### ISSUE THREAD

**Issue by commaender** [VFPX/ExcelXML#4]
In the Save() method of ExcelXML it calls a function named IsObject() -- that function doesn't exist :-)

**Comment by benrojas01** [comment]
tiene un ejemplo de uso?

**Comment by commaender** [comment]
An Example? Well... just look at it... it calls "IsObject()", and "IsObject()" ist not an FoxPro function, and it is not defined in the PRG...

Look at Line# 1342

**Comment by vadpost** [comment]
Need replace "If !IsObject(loExcel)" on    "If !TYPE("loExcel")='O'"

**Comment by mattslay** [comment]
IsObject() has been replaced by Type()
