### ISSUE TITLE
Invalid Reference to ExcelXML.VCX in sample05.prg

### ISSUE THREAD

**Issue by beroniinf** [VFPX/ExcelXML#5]
Hello,
I found a mistake related to the conversion from the VCX class to a PRG.
When calling the NewObject, it still have the reference to ExcelXML.VCX in the sample code
Best regards.
David

*SET PROCEDURE TO ..\excelxml.prg

local loExcelXML, llOk
*loExcelXML = newobject("ExcelXML","ExcelXML.VCX")
loExcelXML = newobject("ExcelXML","..\ExcelXML.prg")

loExcelXML.SheetName = "Students Grade 5A"
loExcelXML.OpenAfterSaving = .t.
llOk = loExcelXML.Save("Sample05.XML")

**Comment by mattslay** [comment]
Fixed.
